# Cargo Configuration
# https://doc.rust-lang.org/cargo/reference/config.html

[build]
# Number of parallel jobs, defaults to # of CPUs
# jobs = 4

# Incremental compilation for faster rebuilds
incremental = true

[target.x86_64-unknown-linux-gnu]
# Linux-specific linker settings
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
# macOS Intel-specific settings
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
# macOS ARM (Apple Silicon) specific settings
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
# Development profile
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256

[profile.release]
# Release profile
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = 'abort'
incremental = false
codegen-units = 1
strip = "symbols"

[profile.bench]
# Benchmark profile
inherits = "release"

[profile.test]
# Test profile
inherits = "dev"

# Aliases for common commands
[alias]
b = "build"
br = "build --release"
t = "test"
c = "check"
cl = "clippy"
r = "run"
rr = "run --release"
fmt-check = "fmt -- --check"
lint = "clippy -- -D warnings"

