[package]
name = "ai-os-kernel"
version = "0.1.0"
edition = "2021"
authors = ["AI-OS Team"]
description = "Lightweight microkernel for AI-Powered OS"

[dependencies]
# Core async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
log = "0.4"
env_logger = "0.11"

# IPC (Inter-Process Communication)
# Will be used to communicate with Python AI service
crossbeam = "0.8"

# Shared state management
parking_lot = "0.12"

[lib]
name = "ai_os_kernel"
path = "src/lib.rs"

[[bin]]
name = "kernel"
path = "src/main.rs"

